---
- name: Install cassandra packages
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: yes
  with_items: '{{ kernel_cassandra_packages }}'
  sudo: yes

- name: Download cassandra
  get_url:
    url: http://www.us.apache.org/dist/cassandra/{{ kernel_cassandra_version }}/apache-cassandra-{{ kernel_cassandra_version }}-bin.tar.gz
    dest: /tmp/apache-cassandra-{{ kernel_cassandra_version }}-bin.tar.gz
    force: yes

- name: Get checksum
  stat:
    path: /tmp/apache-cassandra-{{ kernel_cassandra_version }}-bin.tar.gz
    get_checksum: yes
  sudo: yes
  register: kernel_cassandra_checksum

#- debug: var=kernel_cassandra_checksum.stat.checksum
  #when: kernel_cassandra_installed.stdout != kernel_cassandra_version

#- debug: var=kernel_cassandra_installed
#- debug: var=kernel_cassandra_version

- fail:
    msg: Downloaded cassandra tarball does not have expected checksum.  Intruders!
  when: not kernel_cassandra_checksum.stat.checksum == "393b76f3c597d96697d2163f255a8024d2f22d8d"

- name: Unarchive cassandra
  command: tar -xzvf /tmp/apache-cassandra-{{ kernel_cassandra_version }}-bin.tar.gz -C ~{{ kernel_cassandra_remote_user }}/
