---
kernel_collectd_packages:
  - collectd
  - collectd-utils

# FQDNLookup true is the default.  Use 'Hostname "..."' in your project to
# hard code a value
kernel_collectd_hostname: FQDNLookup true
#kernel_collectd_hostname: Hostname "localhost"

# Seconds
kernel_collectd_default_interval: 10

kernel_collectd_conf_file: /etc/collectd/collectd.conf

kernel_collectd_remote_user: override me

kernel_collectd_log_file: /var/log/collectd.log

# This is used by client (and server to listen to)
kernel_collectd_host: localhost
kernel_collectd_port: 25826

# This is used by server to forward to
kernel_collectd_upstream_host: localhost
kernel_collectd_upstream_port: 25827

kernel_collectd_apt_keyserver: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7543C08D555DC473B9270ACDAF7ECBB3476ACEB3
kernel_collectd_apt_key_id: 476ACEB3
kernel_collectd_apt_repo: ppa:collectd/collectd-5.5

kernel_collectd_network_plugin_auth_user: '{{ kernel_collectd_remote_user }}'
kernel_collectd_network_plugin_auth_password: override me
kernel_collectd_network_plugin_auth_file: /etc/collectd/passwd
kernel_collectd_network_plugin_security_level: Encrypt

kernel_collectd_client_mode: yes
kernel_collectd_server_mode: no

kernel_collectd_plugin_nginx: no
kernel_collectd_plugin_nginx_status_url: https://127.0.0.1/__nginx_status
kernel_collectd_plugin_nginx_verify_peer: 'false'
kernel_collectd_plugin_nginx_verify_host: 'false'
