---
- name: Install collectd packages
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: yes
  with_items: '{{ kernel_collectd_packages }}'
  sudo: yes


- name: Touch log file
  file:
    path: '{{ kernel_collectd_log_file }}'
    owner: '{{ kernel_collectd_remote_user }}'
    group: '{{ kernel_collectd_remote_user }}'
    mode: u=rw,g=r,o=r
    state: touch
  sudo: yes


- name: Place config
  template:
    owner: '{{ kernel_collectd_remote_user }}'
    group: '{{ kernel_collectd_remote_user }}'
    mode: u=rw,g=r,o=r
    backup: yes
    force: yes
    src: collectd.conf
    dest: '{{ kernel_collectd_conf_file }}'
  sudo: yes


- name: Restart collectd
  service:
    name: collectd
    state: restarted
  sudo: yes
