---
- name: Install collectd packages
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: yes
  with_items: '{{ kernel_collectd_packages }}'
  sudo: yes


- name: Restart collectd
  service:
    name: collectd
    state: restarted
  sudo: yes
