---
kernel_postgresql_version: 9.4
kernel_postgresql_packages:
  - postgresql-{{ kernel_postgresql_version }}
  - libpq-dev
  - python-psycopg2

kernel_postgresql_username: override me
kernel_postgresql_password: override me

kernel_postgresql_bootstrap_user: postgres

kernel_postgresql_host: localhost
kernel_postgresql_port: 5432

kernel_postgresql_databases:
  - 'override'

kernel_postgresql_log_prefix: '%t'
